### ISSUE TITLE
Process Hollowing Issues

### ISSUE THREAD

**Issue by aress31** [chvancooten/OSEP-Code-Snippets#7] opened 2022-08-05 00:05 UTC
I followed the instructions for the process hollowing code present in this repo, but when triggering my malware, I get the following error:

```bash
.\meter.hollow.exe                                                                                 in pwsh at 00:57:21
Started 'svchost.exe' in a suspended state with PID 31644. Success: True.
Got process information and located PEB address of process at 0x866010. Success: True.
DEBUG: Executable base address: 0x720000.
DEBUG: e_lfanew offset: 0x7204c8.
DEBUG: RVA offset: 0x7204f0.

Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToUInt32(Byte[] value, Int32 startIndex)
   at ProcessHollowing.Program.Main(String[] args)
```

Any help would be welcome!

**Comment by chvancooten** [comment] 2022-08-05 07:22
This is a duplicate of https://github.com/chvancooten/OSEP-Code-Snippets/issues/5, please compile as x64!

**Closed as completed by chvancooten** 2022-08-05 07:22 UTC
